// <auto-generated />
namespace Books.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig2_publisher_controller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig2_publisher_controller));
        
        string IMigrationMetadata.Id
        {
            get { return "202203011302419_mig2_publisher_controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
