// <auto-generated />
namespace Books.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Photo_Upload1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Photo_Upload1));
        
        string IMigrationMetadata.Id
        {
            get { return "202203081359490_Photo_Upload1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
