// <auto-generated />
namespace Books.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m7_book_class_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m7_book_class_add));
        
        string IMigrationMetadata.Id
        {
            get { return "202203011435462_m7_book_class_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
