// <auto-generated />
namespace Books.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m8_Book_Controller_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m8_Book_Controller_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202203011443498_m8_Book_Controller_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
